<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.lolyay.gma4j</groupId>
        <artifactId>gma4j-parent</artifactId>
        <version>3.14.59</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>gma4j-netty</artifactId>
    <name>GMA4J Netty Transport</name>
    <description>Client-side Netty TCP transport (tcp, gma)</description>

    <dependencies>
        <dependency>
            <groupId>io.lolyay.gma4j</groupId>
            <artifactId>gma4j-shared</artifactId>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

</project>
